spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:8b
        options:
          temperature: 0.7
    vector-store:
      chroma:
        host: localhost
        port: 8000
        collection-name: rag-collection
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:ragdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

server:
  port: 8081
